Pete
FruityRaptors/OneRoof pull request #28
Opened 2021-07-06 06:40 UTC by griffitp12

- Added resolver: **updateHouseModules**, tested with /graphql playground
- Added $store action **adminUpdateModulesList**
- Added button to run the above action on the modules chooser view

In order to use the above functionality:

1. Make your changes to the modules.json file
2. (Close the backend server if you've got it running locally)
2. **NPM Run Build**
3. **NPM Run Build:Server**
4. **NPM Run Start**
5. Navigate to the modules section in the drawer and press the button. You may need to refresh the page to see the functionality.

2021-07-06 07:02 UTC, jaysutham requested changes

2021-07-06 07:02 UTC, jaysutham commented on server/index.ts
> +/*   app.use(express.static(path.resolve(__dirname,"..", "..", "dist")))
Should un-comment these

2021-07-06 07:02 UTC, jaysutham commented on server/index.ts
> +  app.use(express.static(path.resolve(__dirname,"..", "..", "dist"))) */
Should un-comment these

2021-07-06 07:03 UTC, griffitp12 commented on server/index.ts
> +  app.use(express.static(path.resolve(__dirname,"..", "..", "dist"))) */
Yep, you're right

2021-07-06 07:03 UTC, griffitp12 commented on server/index.ts
> +/*   app.use(express.static(path.resolve(__dirname,"..", "..", "dist")))
Yep

2021-07-06 07:36 UTC, jaysutham approved these changes

2021-07-07 13:18 UTC, KuroKen91 approved these changes
LGTM! Thanks Pete!

2021-07-12 04:12 UTC, Evomatic approved these changes
This looks solid!

2021-07-12 04:36 UTC, merged